import fs from 'node:fs';
import {distanceKm} from '../dist/location.js';
function csv(path){const rows=fs.readFileSync(path,'utf8').trim().split(/\r?\n/);const keys=rows.shift().split(',');return rows.map(row=>Object.fromEntries(row.split(',').map((v,i)=>[keys[i],v])));}
const rows=csv('data/stations.csv');rows.push(...csv('data/future-stations-source.csv').filter(r=>['CC30','CC31','CC32'].includes(r.station_code)));
const aliases={'paya-lebar':'paya','raffles-place':'raffles'};
const names={NSL:'North–South Line',EWL:'East–West Line',CGL:'Changi Airport branch',NEL:'North East Line',CCL:'Circle Line',DTL:'Downtown Line',TEL:'Thomson–East Coast Line',BPL:'Bukit Panjang LRT',SLRT:'Sengkang LRT',PLRT:'Punggol LRT'};
const lineFor={NS:'NSL',EW:'EWL',CG:'CGL',NE:'NEL',CC:'CCL',CE:'CCL',DT:'DTL',TE:'TEL',BP:'BPL',SE:'SLRT',SW:'SLRT',STC:'SLRT',PE:'PLRT',PW:'PLRT',PTC:'PLRT'};
const stations={},codes={};
for(const row of rows){let code=row.station_code;if(code==='CE1')code='CC34';if(code==='CE2')code='CC33';const slug=row.station_name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),id=aliases[slug]||slug,prefix=code.replace(/\d/g,''),line=lineFor[prefix];if(!line)continue;const s=stations[id]??={id,name:row.station_name,station:row.station_name,coord:[+row.lon,+row.lat],codes:[],lines:[],walk:3};s.codes.push(code);if(!s.lines.includes(line))s.lines.push(line);codes[code]=id;}
for(const s of Object.values(stations))s.code=s.codes.join(' / ');
const edges=[];
function connect(a,b,line){if(!codes[a]||!codes[b])throw Error(`Missing station ${a}/${b}`);const from=codes[a],to=codes[b];if(from===to)return;for(const id of [from,to])if(!stations[id].lines.includes(line))stations[id].lines.push(line);const minutes=Math.max(line.endsWith('LRT')||line==='BPL'?1:2,Math.round(distanceKm(stations[from].coord,stations[to].coord)/(line.endsWith('LRT')||line==='BPL'?0.35:0.65)+0.7));edges.push({from,to,line,minutes},{from:to,to:from,line,minutes});}
function chain(list,line){for(let i=1;i<list.length;i++)connect(list[i-1],list[i],line);}
function sequence(prefix){return Object.keys(codes).filter(c=>new RegExp('^'+prefix+'[0-9]+$').test(c)).sort((a,b)=>+a.slice(prefix.length)-+b.slice(prefix.length));}
for(const prefix of ['NS','EW','NE','DT','TE'])chain(sequence(prefix),lineFor[prefix]);
chain(['EW4','CG1','CG2'],'CGL');chain(sequence('CC'),'CCL');connect('CC34','CC4','CCL');
chain(sequence('BP'),'BPL');connect('BP13','BP6','BPL');
for(const prefix of ['SE','SW','PE','PW']){const central=prefix[0]==='S'?'STC':'PTC';chain([central,...sequence(prefix),central],lineFor[prefix]);}
const metadata={checked:'2026-09-18',coordinateSource:'https://github.com/elliotwutingfeng/singapore_train_station_coordinates',licence:'Singapore Open Data Licence 1.0',networkSource:'https://www.lta.gov.sg/content/ltagov/en/getting_around/public_transport/rail_network.html',notes:'Station order follows LTA system map. CCL6 added following official 12 July 2026 opening; CC33/CC34 replace CE2/CE1. No future TEL5, DTL3e, JRL or CRL stations. Edge times are uncalibrated distance-based estimates; LRT loops model both directions, not service timetables.'};
fs.writeFileSync('dist/data/network.js',`// Generated by scripts/build-network.mjs. See data/LICENSE-DATASET.md.\nexport const network = ${JSON.stringify({stations,edges,lines:names,metadata})};\n`);
console.log(`${Object.keys(stations).length} stations; ${edges.length} directed edges; ${Object.keys(names).length} rail services`);
